# Generated by Django 3.2.6 on 2021-08-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demirbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, verbose_name='isim')),
                ('stok', models.CharField(max_length=10, verbose_name='Stok')),
                ('device', models.CharField(max_length=20, verbose_name='Cihaz')),
                ('number', models.CharField(max_length=5, verbose_name='Sayı')),
                ('brand', models.CharField(max_length=30, verbose_name='Marka')),
                ('serial', models.CharField(max_length=50, verbose_name='Seri No')),
                ('status', models.CharField(max_length=10, verbose_name='Durumu')),
                ('exp', models.CharField(max_length=100, verbose_name='Açıklama')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
