# Generated by Django 3.2.6 on 2021-08-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demirbas',
            new_name='Kullanıcı',
        ),
    ]
