# Generated by Django 3.2.6 on 2021-08-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0002_rename_demirbas_kullanıcı'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kullanıcı',
            new_name='Çalışan',
        ),
    ]
