# Generated by Django 3.2.6 on 2021-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0004_auto_20210816_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.CharField(max_length=10, verbose_name='Stok')),
                ('device', models.CharField(max_length=20, verbose_name='Cihaz')),
                ('number', models.CharField(max_length=5, verbose_name='Sayı')),
                ('brand', models.CharField(max_length=30, verbose_name='Marka')),
                ('serial', models.CharField(max_length=50, verbose_name='Seri No')),
                ('status', models.CharField(max_length=10, verbose_name='Durumu')),
                ('exp', models.CharField(max_length=100, verbose_name='Açıklama')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='device',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='number',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='status',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='stok',
        ),
    ]
