# Generated by Django 3.2.6 on 2021-08-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0005_auto_20210817_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
