# Generated by Django 3.2.6 on 2021-08-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0006_alter_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Demirbaş_App.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
