# Generated by Django 3.2.6 on 2021-08-17 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0007_auto_20210817_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
            preserve_default=False,
        ),
    ]
