# Generated by Django 3.2.6 on 2021-08-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0009_auto_20210817_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='personD',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='personW',
            new_name='person',
        ),
    ]
