# Generated by Django 3.2.6 on 2021-08-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0010_auto_20210817_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='stok',
            field=models.CharField(max_length=10, null=True, verbose_name='Stok'),
        ),
    ]
