# Generated by Django 3.2.6 on 2021-08-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0011_alter_device_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='stok',
            field=models.CharField(blank=True, max_length=10, verbose_name='Stok'),
        ),
    ]
