# Generated by Django 3.2.6 on 2021-08-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0013_auto_20210818_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=30, verbose_name='Model'),
        ),
    ]
