# Generated by Django 3.2.6 on 2021-08-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0014_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cihaz'),
        ),
        migrations.AlterField(
            model_name='device',
            name='exp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='device',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Sayı'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Seri No'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Durumu'),
        ),
        migrations.AlterField(
            model_name='device',
            name='stok',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Stok'),
        ),
    ]
