# Generated by Django 3.2.6 on 2021-08-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0015_auto_20210818_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='device',
            name='person_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Demirbaş_App.worker'),
        ),
    ]
