# Generated by Django 3.2.6 on 2021-08-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0017_auto_20210818_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='person_id',
        ),
    ]
