# Generated by Django 3.2.6 on 2021-08-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0018_auto_20210818_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Demirbaş_App.worker'),
        ),
    ]
