# Generated by Django 3.2.6 on 2021-08-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0019_device_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='person_id',
        ),
    ]
