# Generated by Django 3.2.6 on 2021-08-18 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0020_remove_device_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Demirbaş_App.worker'),
        ),
    ]
