# Generated by Django 3.2.6 on 2021-08-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0021_auto_20210818_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='person_id',
            field=models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, to='Demirbaş_App.worker'),
        ),
    ]
