# Generated by Django 3.2.6 on 2021-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0023_alter_device_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cihaz'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Durumu'),
        ),
    ]
