# Generated by Django 3.2.6 on 2021-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0024_auto_20210819_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='stok',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Stok'),
        ),
    ]
