# Generated by Django 3.2.6 on 2021-08-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0025_alter_device_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_date',
        ),
    ]
