# Generated by Django 3.2.6 on 2021-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0026_remove_device_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
