# Generated by Django 3.2.6 on 2021-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0027_worker_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='admin',
            new_name='couser',
        ),
        migrations.AddField(
            model_name='worker',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
