# Generated by Django 3.2.6 on 2021-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0028_auto_20210826_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='couser',
        ),
    ]
