# Generated by Django 3.2.6 on 2021-08-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0029_remove_worker_couser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='created_date',
        ),
    ]
