# Generated by Django 3.2.6 on 2021-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0030_remove_worker_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='take_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alım Tarihi'),
        ),
        migrations.AddField(
            model_name='device',
            name='zim_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zimmet Tarihi'),
        ),
    ]
