# Generated by Django 3.2.6 on 2021-09-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0032_excel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Excel',
        ),
    ]
