# Generated by Django 3.2.6 on 2021-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0033_delete_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Fiyat'),
        ),
    ]
