# Generated by Django 3.2.6 on 2021-09-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0034_device_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='iz',
            field=models.CharField(blank=True, max_length=100000000, null=True, verbose_name='İz'),
        ),
    ]
