# Generated by Django 3.2.6 on 2021-09-14 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Demirbaş_App', '0035_device_iz'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='İşlem Türü')),
                ('stok', models.CharField(blank=True, max_length=30, null=True, verbose_name='Stok')),
                ('device', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cihaz')),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
