# Generated by Django 3.2.6 on 2021-09-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0036_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='who',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kullanıcı Adı'),
        ),
    ]
