# Generated by Django 3.2.6 on 2021-09-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0037_alter_history_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='device',
        ),
        migrations.RemoveField(
            model_name='history',
            name='operation_date',
        ),
        migrations.RemoveField(
            model_name='history',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='history',
            name='stok',
        ),
    ]
