# Generated by Django 3.2.6 on 2021-09-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0038_auto_20210914_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
