# Generated by Django 3.2.6 on 2021-09-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0039_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kullanıcı Adı')),
                ('operation_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='İşlem Türü')),
                ('stok', models.CharField(blank=True, max_length=30, null=True, verbose_name='Stok')),
                ('device', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cihaz')),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
