# Generated by Django 3.2.6 on 2021-09-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0040_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='operation_date',
            field=models.DateTimeField(),
        ),
    ]
