# Generated by Django 3.2.6 on 2021-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0041_alter_history_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='operation_date',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tarih'),
        ),
    ]
