# Generated by Django 3.2.6 on 2021-09-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demirbaş_App', '0036_alter_device_iz'),
        ('Demirbaş_App', '0042_alter_history_operation_date'),
    ]

    operations = [
    ]
