# Generated by Django 3.2.6 on 2021-08-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demirbasobje',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Ekleyen Kişi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demirbasobje',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='demirbasobje',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Nesne Türü'),
        ),
    ]
